<?php

if (!function_exists('demo_mock_seed')) {
    function demo_mock_seed(): array
    {
        $now = date('Y-m-d H:i:s');

        return [
            'users' => [
                [
                    'id' => 'usr_gerente_001',
                    'username' => '45871234',
                    'password' => '45871234',
                    'full_name' => 'María Fernanda López',
                    'role' => 'gerente',
                    'document' => '45871234',
                    'email' => 'maria.lopez@brokerdemo.com',
                    'phone' => '999111222',
                    'status' => 'activo',
                    'avatar' => 'ML',
                    'client_id' => null,
                    'assigned_executive_user_id' => null,
                    'created_at' => '2026-01-02 08:30:00',
                ],
                [
                    'id' => 'usr_ejecutivo_001',
                    'username' => '48652137',
                    'password' => '48652137',
                    'full_name' => 'Carlos Eduardo Ramos',
                    'role' => 'ejecutivo',
                    'document' => '48652137',
                    'email' => 'carlos.ramos@brokerdemo.com',
                    'phone' => '998222333',
                    'status' => 'activo',
                    'avatar' => 'CR',
                    'client_id' => null,
                    'assigned_executive_user_id' => null,
                    'created_at' => '2026-01-03 09:00:00',
                ],
                [
                    'id' => 'usr_cliente_001',
                    'username' => '70123456',
                    'password' => '70123456',
                    'full_name' => 'Javier Enrique Salas',
                    'role' => 'cliente',
                    'document' => '70123456',
                    'email' => 'javier.salas@gmail.com',
                    'phone' => '987654321',
                    'status' => 'activo',
                    'avatar' => 'JS',
                    'client_id' => 'cli_001',
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'created_at' => '2026-01-10 10:15:00',
                ],
            ],

            'clients' => [
                [
                    'id' => 'cli_001',
                    'type' => 'persona',
                    'name' => 'Javier Enrique Salas',
                    'document_type' => 'DNI',
                    'document_number' => '70123456',
                    'email' => 'javier.salas@gmail.com',
                    'phone' => '987654321',
                    'address' => 'Av. Primavera 215, Surco',
                    'status' => 'activo',
                    'has_portal_access' => true,
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'notes' => 'Cliente puntual en pagos y prefiere contacto por WhatsApp.',
                    'created_at' => '2026-01-10 10:00:00',
                ],
                [
                    'id' => 'cli_002',
                    'type' => 'persona',
                    'name' => 'Lucía Torres Mendoza',
                    'document_type' => 'DNI',
                    'document_number' => '74561238',
                    'email' => 'lucia.torres@gmail.com',
                    'phone' => '989222444',
                    'address' => 'Calle Los Sauces 110, San Borja',
                    'status' => 'activo',
                    'has_portal_access' => false,
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'notes' => 'Interesada en ampliar cobertura de hogar.',
                    'created_at' => '2026-01-12 11:00:00',
                ],
                [
                    'id' => 'cli_003',
                    'type' => 'empresa',
                    'name' => 'Comercial Andina SAC',
                    'document_type' => 'RUC',
                    'document_number' => '20561234981',
                    'email' => 'administracion@andina.pe',
                    'phone' => '014521245',
                    'address' => 'Jr. Unión 450, Cercado de Lima',
                    'status' => 'activo',
                    'has_portal_access' => false,
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'notes' => 'Empresa con pólizas empresariales y RC.',
                    'created_at' => '2026-01-15 08:30:00',
                ],
                [
                    'id' => 'cli_004',
                    'type' => 'persona',
                    'name' => 'Renato Paredes Silva',
                    'document_type' => 'DNI',
                    'document_number' => '71234988',
                    'email' => 'renato.paredes@gmail.com',
                    'phone' => '955333111',
                    'address' => 'Av. Benavides 904, Miraflores',
                    'status' => 'inactivo',
                    'has_portal_access' => false,
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'notes' => 'Pendiente de renovación desde febrero.',
                    'created_at' => '2026-02-02 09:40:00',
                ],
                [
                    'id' => 'cli_005',
                    'type' => 'empresa',
                    'name' => 'Grupo Logístico del Sur EIRL',
                    'document_type' => 'RUC',
                    'document_number' => '20601567843',
                    'email' => 'operaciones@gls.pe',
                    'phone' => '013954210',
                    'address' => 'Parque Industrial Mz. C, Villa El Salvador',
                    'status' => 'activo',
                    'has_portal_access' => false,
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'notes' => 'Solicitó propuesta para flota vehicular.',
                    'created_at' => '2026-02-08 12:10:00',
                ],
                [
                    'id' => 'cli_006',
                    'type' => 'persona',
                    'name' => 'Carla Díaz Herrera',
                    'document_type' => 'DNI',
                    'document_number' => '73659841',
                    'email' => 'carla.diaz@gmail.com',
                    'phone' => '966781245',
                    'address' => 'Av. Ejército 300, Magdalena',
                    'status' => 'activo',
                    'has_portal_access' => false,
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'notes' => 'Cliente nueva con seguro vehicular.',
                    'created_at' => '2026-03-01 14:00:00',
                ],
            ],

            'insurers' => [
                ['id' => 'ins_001', 'name' => 'Rímac Seguros', 'status' => 'activo'],
                ['id' => 'ins_002', 'name' => 'Pacífico Seguros', 'status' => 'activo'],
                ['id' => 'ins_003', 'name' => 'Mapfre Perú', 'status' => 'activo'],
                ['id' => 'ins_004', 'name' => 'La Positiva', 'status' => 'activo'],
            ],

            'insurance_types' => [
                ['id' => 'type_001', 'name' => 'Auto', 'status' => 'activo'],
                ['id' => 'type_002', 'name' => 'Salud', 'status' => 'activo'],
                ['id' => 'type_003', 'name' => 'Vida', 'status' => 'activo'],
                ['id' => 'type_004', 'name' => 'Hogar', 'status' => 'activo'],
                ['id' => 'type_005', 'name' => 'Empresa', 'status' => 'activo'],
            ],

            'policy_statuses' => [
                ['id' => 'pst_001', 'name' => 'activa', 'status' => 'activo'],
                ['id' => 'pst_002', 'name' => 'pendiente', 'status' => 'activo'],
                ['id' => 'pst_003', 'name' => 'vencida', 'status' => 'activo'],
                ['id' => 'pst_004', 'name' => 'anulada', 'status' => 'activo'],
                ['id' => 'pst_005', 'name' => 'renovada', 'status' => 'activo'],
            ],

            'installment_statuses' => [
                ['id' => 'ist_001', 'name' => 'pendiente', 'status' => 'activo'],
                ['id' => 'ist_002', 'name' => 'pagada', 'status' => 'activo'],
                ['id' => 'ist_003', 'name' => 'vencida', 'status' => 'activo'],
                ['id' => 'ist_004', 'name' => 'en revisión', 'status' => 'activo'],
            ],

            'claim_statuses' => [
                ['id' => 'cst_001', 'name' => 'reportado', 'status' => 'activo'],
                ['id' => 'cst_002', 'name' => 'en revisión', 'status' => 'activo'],
                ['id' => 'cst_003', 'name' => 'pendiente documentos', 'status' => 'activo'],
                ['id' => 'cst_004', 'name' => 'cerrado', 'status' => 'activo'],
            ],

            'internal_categories' => [
                ['id' => 'cat_001', 'name' => 'VIP', 'status' => 'activo'],
                ['id' => 'cat_002', 'name' => 'Renovación próxima', 'status' => 'activo'],
                ['id' => 'cat_003', 'name' => 'Morosidad', 'status' => 'activo'],
                ['id' => 'cat_004', 'name' => 'Venta cruzada', 'status' => 'activo'],
            ],

            'policies' => [
                [
                    'id' => 'pol_001',
                    'policy_number' => 'AU-2026-000145',
                    'client_id' => 'cli_001',
                    'insurer_id' => 'ins_001',
                    'insurance_type_id' => 'type_001',
                    'status' => 'activa',
                    'premium' => 2450.00,
                    'currency' => 'S/',
                    'start_date' => '2026-01-01',
                    'end_date' => '2026-12-31',
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'insured_item' => 'Toyota Corolla 2022 - Placa BXY-123',
                    'notes' => 'Cobertura completa con asistencia vial.',
                    'created_at' => '2026-01-02 10:00:00',
                ],
                [
                    'id' => 'pol_002',
                    'policy_number' => 'HO-2026-000054',
                    'client_id' => 'cli_002',
                    'insurer_id' => 'ins_002',
                    'insurance_type_id' => 'type_004',
                    'status' => 'activa',
                    'premium' => 1680.00,
                    'currency' => 'S/',
                    'start_date' => '2026-02-01',
                    'end_date' => '2027-01-31',
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'insured_item' => 'Departamento en San Borja',
                    'notes' => 'Incluye cobertura contra incendio y robo.',
                    'created_at' => '2026-02-01 09:20:00',
                ],
                [
                    'id' => 'pol_003',
                    'policy_number' => 'EM-2026-000032',
                    'client_id' => 'cli_003',
                    'insurer_id' => 'ins_003',
                    'insurance_type_id' => 'type_005',
                    'status' => 'activa',
                    'premium' => 5400.00,
                    'currency' => 'S/',
                    'start_date' => '2026-01-15',
                    'end_date' => '2027-01-14',
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'insured_item' => 'Póliza empresarial multirriesgo',
                    'notes' => 'Cobertura con responsabilidad civil y daños a terceros.',
                    'created_at' => '2026-01-15 12:30:00',
                ],
                [
                    'id' => 'pol_004',
                    'policy_number' => 'LI-2026-000028',
                    'client_id' => 'cli_004',
                    'insurer_id' => 'ins_004',
                    'insurance_type_id' => 'type_003',
                    'status' => 'vencida',
                    'premium' => 980.00,
                    'currency' => 'S/',
                    'start_date' => '2025-02-01',
                    'end_date' => '2026-01-31',
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'insured_item' => 'Vida individual',
                    'notes' => 'Pendiente propuesta de renovación.',
                    'created_at' => '2025-02-01 08:15:00',
                ],
                [
                    'id' => 'pol_005',
                    'policy_number' => 'AU-2026-000211',
                    'client_id' => 'cli_006',
                    'insurer_id' => 'ins_003',
                    'insurance_type_id' => 'type_001',
                    'status' => 'pendiente',
                    'premium' => 2190.00,
                    'currency' => 'S/',
                    'start_date' => '2026-03-10',
                    'end_date' => '2027-03-09',
                    'assigned_executive_user_id' => 'usr_ejecutivo_001',
                    'insured_item' => 'Kia Soluto 2023 - Placa CDF-818',
                    'notes' => 'Pendiente confirmación de pago de primera cuota.',
                    'created_at' => '2026-03-10 16:00:00',
                ],
            ],

            'installments' => [
                [
                    'id' => 'cuo_001',
                    'policy_id' => 'pol_001',
                    'number' => 1,
                    'due_date' => '2026-01-10',
                    'amount' => 204.17,
                    'status' => 'pagada',
                    'receipt_uploaded' => true,
                ],
                [
                    'id' => 'cuo_002',
                    'policy_id' => 'pol_001',
                    'number' => 2,
                    'due_date' => '2026-02-10',
                    'amount' => 204.17,
                    'status' => 'pagada',
                    'receipt_uploaded' => true,
                ],
                [
                    'id' => 'cuo_003',
                    'policy_id' => 'pol_001',
                    'number' => 3,
                    'due_date' => '2026-03-10',
                    'amount' => 204.17,
                    'status' => 'pendiente',
                    'receipt_uploaded' => false,
                ],
                [
                    'id' => 'cuo_004',
                    'policy_id' => 'pol_002',
                    'number' => 1,
                    'due_date' => '2026-02-05',
                    'amount' => 140.00,
                    'status' => 'pagada',
                    'receipt_uploaded' => true,
                ],
                [
                    'id' => 'cuo_005',
                    'policy_id' => 'pol_002',
                    'number' => 2,
                    'due_date' => '2026-03-05',
                    'amount' => 140.00,
                    'status' => 'vencida',
                    'receipt_uploaded' => false,
                ],
                [
                    'id' => 'cuo_006',
                    'policy_id' => 'pol_003',
                    'number' => 1,
                    'due_date' => '2026-01-20',
                    'amount' => 450.00,
                    'status' => 'pagada',
                    'receipt_uploaded' => true,
                ],
                [
                    'id' => 'cuo_007',
                    'policy_id' => 'pol_003',
                    'number' => 2,
                    'due_date' => '2026-02-20',
                    'amount' => 450.00,
                    'status' => 'en revisión',
                    'receipt_uploaded' => true,
                ],
                [
                    'id' => 'cuo_008',
                    'policy_id' => 'pol_005',
                    'number' => 1,
                    'due_date' => '2026-03-15',
                    'amount' => 182.50,
                    'status' => 'pendiente',
                    'receipt_uploaded' => false,
                ],
            ],

            'payments' => [
                [
                    'id' => 'pay_001',
                    'installment_id' => 'cuo_001',
                    'policy_id' => 'pol_001',
                    'client_id' => 'cli_001',
                    'amount' => 204.17,
                    'date' => '2026-01-09',
                    'method' => 'Transferencia',
                    'status' => 'confirmado',
                ],
                [
                    'id' => 'pay_002',
                    'installment_id' => 'cuo_002',
                    'policy_id' => 'pol_001',
                    'client_id' => 'cli_001',
                    'amount' => 204.17,
                    'date' => '2026-02-09',
                    'method' => 'Yape',
                    'status' => 'confirmado',
                ],
                [
                    'id' => 'pay_003',
                    'installment_id' => 'cuo_004',
                    'policy_id' => 'pol_002',
                    'client_id' => 'cli_002',
                    'amount' => 140.00,
                    'date' => '2026-02-04',
                    'method' => 'Transferencia',
                    'status' => 'confirmado',
                ],
            ],

            'claims' => [
                [
                    'id' => 'sin_001',
                    'code' => 'SIN-2026-0012',
                    'client_id' => 'cli_001',
                    'policy_id' => 'pol_001',
                    'type' => 'Choque leve',
                    'date' => '2026-02-14',
                    'status' => 'en revisión',
                    'assigned_user_id' => 'usr_ejecutivo_001',
                    'description' => 'Golpe en parachoques delantero en estacionamiento.',
                    'notes' => 'Pendiente fotos del vehículo tercero.',
                ],
                [
                    'id' => 'sin_002',
                    'code' => 'SIN-2026-0018',
                    'client_id' => 'cli_003',
                    'policy_id' => 'pol_003',
                    'type' => 'Daño por agua',
                    'date' => '2026-03-01',
                    'status' => 'pendiente documentos',
                    'assigned_user_id' => 'usr_ejecutivo_001',
                    'description' => 'Filtración en almacén principal.',
                    'notes' => 'Pendiente informe técnico y cotización.',
                ],
            ],

            'documents' => [
                [
                    'id' => 'doc_001',
                    'entity_type' => 'policy',
                    'entity_id' => 'pol_001',
                    'name' => 'poliza_auto_javier_salas.pdf',
                    'original_name' => 'Póliza Auto Javier Salas.pdf',
                    'type' => 'Póliza',
                    'uploaded_by' => 'usr_ejecutivo_001',
                    'created_at' => '2026-01-02 10:05:00',
                ],
                [
                    'id' => 'doc_002',
                    'entity_type' => 'client',
                    'entity_id' => 'cli_001',
                    'name' => 'dni_javier_salas.jpg',
                    'original_name' => 'DNI Javier Salas.jpg',
                    'type' => 'DNI',
                    'uploaded_by' => 'usr_ejecutivo_001',
                    'created_at' => '2026-01-10 10:20:00',
                ],
                [
                    'id' => 'doc_003',
                    'entity_type' => 'claim',
                    'entity_id' => 'sin_001',
                    'name' => 'foto_choque_001.png',
                    'original_name' => 'Foto Choque 001.png',
                    'type' => 'Evidencia',
                    'uploaded_by' => 'usr_cliente_001',
                    'created_at' => '2026-02-14 18:10:00',
                ],
            ],

            'notifications' => [
                [
                    'id' => 'not_001',
                    'user_id' => 'usr_gerente_001',
                    'title' => 'Cuota vencida',
                    'message' => 'La póliza HO-2026-000054 tiene una cuota vencida.',
                    'type' => 'warning',
                    'read' => false,
                    'created_at' => '2026-03-05 09:00:00',
                ],
                [
                    'id' => 'not_002',
                    'user_id' => 'usr_ejecutivo_001',
                    'title' => 'Nuevo siniestro',
                    'message' => 'Javier Salas reportó un nuevo siniestro.',
                    'type' => 'info',
                    'read' => false,
                    'created_at' => '2026-02-14 18:15:00',
                ],
                [
                    'id' => 'not_003',
                    'user_id' => 'usr_cliente_001',
                    'title' => 'Pago pendiente',
                    'message' => 'Tu cuota 3 vence el 10/03/2026.',
                    'type' => 'warning',
                    'read' => false,
                    'created_at' => '2026-03-07 08:00:00',
                ],
            ],

            'activity_log' => [
                [
                    'id' => 'act_001',
                    'title' => 'Póliza creada',
                    'description' => 'Se registró la póliza AU-2026-000145 para Javier Salas.',
                    'user_id' => 'usr_ejecutivo_001',
                    'created_at' => '2026-01-02 10:00:00',
                ],
                [
                    'id' => 'act_002',
                    'title' => 'Pago confirmado',
                    'description' => 'Se confirmó el pago de la cuota 2 de AU-2026-000145.',
                    'user_id' => 'usr_gerente_001',
                    'created_at' => '2026-02-09 11:30:00',
                ],
                [
                    'id' => 'act_003',
                    'title' => 'Siniestro reportado',
                    'description' => 'Se abrió el caso SIN-2026-0012.',
                    'user_id' => 'usr_cliente_001',
                    'created_at' => '2026-02-14 18:15:00',
                ],
            ],

            'meta' => [
                'seeded_at' => $now,
            ],
        ];
    }
}